ERRORs should go to stderr

diff --git a/cmc b/cmc
--- a/cmc
+++ b/cmc
@@ -272,7 +272,7 @@ session_open() {
             if [[ -n "${syslog:-}" ]]
             then
                 _error=$(grep -F ' ssh: ' /var/log/system.log | tail -n 1)
-                echo "ERROR: ${_error#*error:}"
+                echo "ERROR: ${_error#*error:}" 1>&2
             fi
             return ${_es}
         fi
